source 'https://rubygems.org'

gem 'telegram-bot-ruby'
gem 'activerecord', '< 6.2.0'
gem 'faraday', '~> 0.9.2'
gem 'standalone_migrations', github: 'thuss/standalone-migrations'
gem 'i18n'
gem 'sqlite3'
gem 'rake'
gem 'rerun'
gem 'debase'
gem 'ruby-debug-ide'