en:
  start: "Hi! Telegram is awesome!"
  stop: "Bye! I'll miss you :("
  help: "
    /create -

    /deploy (:branch:) -

    /list

    /restart -
  "
  created: Project "%{name}" with Github %{github} created!